### ISSUE TITLE
docker-hub

### ISSUE THREAD

**Issue by progrium** [tractordev/integra#3]
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/docker.com/hub/beta/openapi.yaml

**Comment by lritter79** [comment]
https://docs.docker.com/reference/api/hub/latest/

**Comment by lritter79** [comment]
Some info fields missing:
```
Title:         Docker HUB API
Provider:      
Version:       beta
Data Scope:    mixed
Categories:    
Security:      
Base URL:      https://hub.docker.com/
Docs URL:      
```

**Comment by lritter79** [comment]
Error on running `./local/integra describe --resources docker-hub`
```
2024/11/21 15:06:32 openapi.go:328: !! unknown operation for 'parameters /v2/access-tokens/{uuid}'
2024/11/21 15:06:32 openapi.go:328: !! unknown operation for 'head /v2/namespaces/{namespace}/repositories/{repository}/tags'
2024/11/21 15:06:32 openapi.go:328: !! unknown operation for 'parameters /v2/namespaces/{namespace}/repositories/{repository}/tags'
2024/11/21 15:06:32 openapi.go:328: !! unknown operation for 'head /v2/namespaces/{namespace}/repositories/{repository}/tags/{tag}'
2024/11/21 15:06:32 openapi.go:328: !! unknown operation for 'parameters /v2/namespaces/{namespace}/repositories/{repository}/tags/{tag}'
2024/11/21 15:06:32 openapi.go:328: !! unknown operation for 'parameters /v2/orgs/{name}/settings'
2024/11/21 15:06:32 openapi.go:328: !! unknown operation for 'parameters /v2/scim/2.0/Users/{id}'
```

**Comment by lritter79** [comment]
"."s in Scim section names:
```

SCIM
  scim2.0Resourcetype
  scim2.0Schema
  scim2.0Serviceproviderconfig
  scim2.0User
```

**Comment by lritter79** [comment]
for `./local/integra describe docker-hub.namespaceRepositoryTag.list` output should be an array of objects, instead it returned to following output below

```
=== OPERATION OUTPUT
object:
  count       integer    total number of results available across all pages
  next        string     link to next page of results if any
  previous    string     link to previous page of results  if any
  results     array      
```

**Comment by lritter79** [comment]
Auth works with a bearer token  and there are personal access token, see [here](https://docs.docker.com/reference/api/hub/latest/#tag/authentication) and [here](https://docs.docker.com/reference/api/hub/latest/#tag/access-tokens/paths/~1v2~1access-tokens/post)  to create one

**Comment by lritter79** [comment]
Potential issue, but not sure @progrium 
Ran ` ./local/integra describe docker-hub.namespaceRepositoryTag` and got some weird methods titled `??head` in the output. 
```
=== RESOURCE INFO
Title:              NamespaceRepositoryTag
Tags:               repositories
Orientation:        absolute
Collection URLs:    https://hub.docker.com/v2/namespaces/{namespace}/repositories/{repository}/tags
Item URLs:          https://hub.docker.com/v2/namespaces/{namespace}/repositories/{repository}/tags/{tag}

=== RESOURCE OPERATIONS
list      List repository tags
??head    Check repository tags
get       Read repository tag
??head    Check repository tag
```

**Comment by lritter79** [comment]
> "."s in Scim section names:
> 
> ```
> 
> SCIM
>   scim2.0Resourcetype
>   scim2.0Schema
>   scim2.0Serviceproviderconfig
>   scim2.0User
> ```

Running these resources didnt work, get error: `2024/11/22 14:46:26 describe.go:55: resource 'scim2' not found`

**Comment by progrium** [comment]
"??head" was resolved, good catch. they should show up as "check" now, but in this case there will be two with the same name. this would normally be an issue if you see this in the future, but its fine for now since i'm working on a fix. we'll block on it next time you see it. 

resource names should have "."'s removed now so it won't get confused parsing the selector, so the scim resources should be ok now. "scim20Resourcetype" is not an ideal name, but i have a note to improve it later. 

and then the resolver issue was fixed, that was a bug in handling nested references in the schema.
